# Generated by Django 5.0.1 on 2024-07-17 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devtools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ideas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('ideaImage', models.ImageField(null=True, upload_to='')),
                ('content', models.CharField(max_length=20000)),
                ('interset', models.IntegerField(default=0)),
                ('devtool', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='devtools.devtools')),
            ],
        ),
    ]
