# Generated by Django 5.0.1 on 2024-07-17 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ideas',
            name='ideaImage',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
