# Generated by Django 5.0.6 on 2024-07-12 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='openingDate',
            field=models.CharField(max_length=20),
        ),
    ]
